apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: rospo
spec:
  type: LoadBalancer
  selector:
    app: rospo
  ports:
    - protocol: TCP
      port: 22
      targetPort: 2222
  