apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: rospo
spec:
  type: LoadBalancer
  selector:
    app: rospo
  ports:
    - protocol: TCP
      name: rospo
      port: 22
      targetPort: 2222
    # wireguard
    # - protocol: UDP
    #   name: wireguard
    #   port: 51820
    #   targetPort: 51820
  