kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: docker-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
